name: Prevent modifying login.toml

on: [push, pull_request]

jobs:
  documentation:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Prevent modifying login.toml
      uses: xalvarez/prevent-file-change-action@v1.6.0
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        pattern: login.toml
